<img src="./figures/pylogo.png" alt="Indentation" width="50%" height="50%">



# 2 Python training: List() 

The most basic data structure in Python is the sequence. 

Python has six built-in types of sequences, but the most common ones are lists and tuples, which we would see in this tutorial.

There are certain things you can do with all sequence types. These operations include indexing, slicing, adding, multiplying. In addition, Python has built-in functions for finding the length of a sequence and for finding its largest and smallest elements.

Each element of a sequence is assigned a number - its position or index. The first index is zero, the second index is one...

Creating a list is as simple as putting different comma-separated values between square brackets : 

             - list1 = [ a, b, c, d, e]
             - list2 = [ 1, 2, 3, 4, 5]


Python is an object-oriented language, lists are associated with methods: object.method()

Functions can be applied to lists. 


## 2.1 Create a list

To create a list, we use comma-separated values between square brackets.

In [2]:
my_list = [1,2,3,4,5,6,7,8,"hello",10.5]

In [3]:
print(my_list)  # fonction to print elements in list 

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5]


We can use <b>range()</b> function to generate a sequence of numbers over time.

In [4]:
my_list = list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
my_list = list(range(1981,2011,2))
my_list

[1981,
 1983,
 1985,
 1987,
 1989,
 1991,
 1993,
 1995,
 1997,
 1999,
 2001,
 2003,
 2005,
 2007,
 2009]

When we work with Python object, dir() command always shows us the tasks we can do with this object: dir(my_list)

In [6]:
dir(my_list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## 2.2 Accessing Values in Lists : 

To access values in lists, use the square brackets for slicing along with the index or indices to obtain value available at that index.

The first index is zero, the second index is one... to read first element, we use index 0. To read last element, we use -1 index. 

It is also possible to modify a value with its index.

In [7]:
my_list = [1,2,3,4,5,6,7,8,"hello",10.5]
my_list[:]  # To use all elements

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5]

In [7]:
my_list[1] # to access an item from the list: here we access the second element. 

2

In [8]:
my_list[2:4] # slicing:  to access the elements between the 3rd position and the 4th


[3, 4]

In [9]:
my_list[:4] # slicing: to access all elements up to index 4 or 4th position

[1, 2, 3, 4]

In [10]:
my_list[3:] # slicing: to access all elements from index 3

[4, 5, 6, 7, 8, 'hello', 10.5]

In [12]:
my_list[-2] # to get the 2nd value from the end, with use negative indexes, we do not start from 0 anymore.


'hello'

In [12]:
my_list[1:-4] # we start from the index 1, with slicing, we stop at the 4th index from the end

[2, 3, 4, 5, 6]

In [14]:
my_list[::2] # to extract the elements with an increment

[1, 3, 5, 7, 'hello']

In [15]:
ma_liste[1::2] # to extract the elements with an increment

[2, 4, 6, 8, 10.5]

## 2.3 Updating Lists

### 2.3.1 Add elements
To <b>add</b> an element: we use <b>append</b> method

In [24]:
my_list = [1,2,3,4,5,6,7,8,"hello",10.5]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5]

In [25]:
my_list.append(2)

In [26]:
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5, 2]


In [27]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5, 2]

### 2.3.2 Insert elements

To <b>insert</b> an element to our list using index: <b>insert()</b> method

In [28]:
my_list.insert(5,"new")

In [29]:
print(my_list)

[1, 2, 3, 4, 5, 'new', 6, 7, 8, 'hello', 10.5, 2]


### 2.3.3 Update elements

To <b>change</b> an element in our list using index

In [30]:
my_list[0]="a"

In [32]:
print(my_list)

['a', 2, 3, 4, 5, 'new', 6, 7, 8, 'hello', 10.5, 2]


To <b>change</b> several elements in our list: slicing

In [33]:
my_list[3:5]=[8,10,11,22]

In [34]:
print(my_list)

['a', 2, 3, 8, 10, 11, 22, 'new', 6, 7, 8, 'hello', 10.5, 2]


### 2.3.4 Remove elements

To <b>remove</b> in our list: 2 methods 

In [35]:
my_list[0:2]=[]  # remove using slicing 
print(my_list)

[3, 8, 10, 11, 22, 'new', 6, 7, 8, 'hello', 10.5, 2]


In [27]:
my_list

[3, 8, 10, 11, 22, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]

In [36]:
del my_list[3] # to remove using keywords

In [37]:
print(my_list)

[3, 8, 10, 22, 'new', 6, 7, 8, 'hello', 10.5, 2]


https://www.programiz.com/python-programming/keyword-list

## 2.4  Useful operations on lists

- Concatenate two lists

In [1]:
my_list1=[1,2,3,4,5]

In [2]:
my_list2=[6,7,8,9,10]

In [3]:
my_list3=my_list1+my_list2

In [4]:
my_list3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

- Duplicate a list

In [5]:
my_list1=[1,2,3,4,5]
my_list1*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

-  Reverse elements in list

<b>.reverse()</b> method is used to reverse elements in list

In [44]:
my_list1=[1,2,3,4,5]
print(my_list1)
my_list1.reverse()
print(my_list1)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


- Count elements in list

<b>.count()</b> method is used to return count of how many times obj occurs in list.

In [45]:
my_list2= ["a","a","a","b","c","c"]
my_list2.count("a")

3


- <b>.index()</b> method returns the lowest index in list that obj appears

In [46]:
my_list2=["a","a","a","b","c","c"]
my_list2.index("c")

4

- function <b>sum()</b>

In [47]:
my_list1=[1,2,3,4,5]
sum(my_list1)

15

- function <b>.len()</b> gives the total length of the list.

In [49]:
len(my_list1)

5

- <b>.sort()</b> function to sort objects of list

In [50]:
my_list = [90,3,8,4,1,10,25,99]
my_list.sort() 

In [51]:
my_list

[1, 3, 4, 8, 10, 25, 90, 99]

In [52]:
my_list = [90,3,8,4,1,10,25,99]
my_list

[90, 3, 8, 4, 1, 10, 25, 99]

In [53]:
my_list.sort()

In [54]:
my_list.reverse()

In [55]:
my_list

[99, 90, 25, 10, 8, 4, 3, 1]

- <b>min()</b> and <b>max()</b> functions to return the <b>minimum</b> and the <b>maximum</b> from list

In [56]:
my_list

[99, 90, 25, 10, 8, 4, 3, 1]

In [57]:
min(my_list)

1

In [58]:
max(my_list)

99

- example applying a loop <b>for</b> and <b>print()</b> function to return values from a list

In [59]:
list_month = ["jan","feb","mar"]
for month in list_month:
    print(month)

jan
feb
mar


- <b>enumerate()</b> function to return values and index

In [60]:
list_month = ["jan","feb","mar"]
for month in enumerate(list_month):
     print(month)

(0, 'jan')
(1, 'feb')
(2, 'mar')


- <b>.split()</b> method to transform string into list 

In [61]:
my_string = "January-February-March"
my_string.split("-")

['January', 'February', 'March']

- <b>.join()</b> method to transform list into string

In [63]:
list1 = ['January', 'February', 'March']
":".join(list1)

'January:February:March'

## 2.5 Tuples

- 1 tuple is a list, a set of stored values, but with the difference that a tuple can not be modified as in a list.

- the interest of a tuple is what is stored in a tuple will never be modifiable

- We write all the elements of a tuple by separating them with commas and all surrounded by parentheses:
             - my_tuple = (,,,,)
             
We will use a tuple to define some kinds of constants that are not intended to change

In [53]:
tuple1=(1,2,3,4,5)

In [54]:
tuple1

(1, 2, 3, 4, 5)

In [64]:
tuple1[0]=0 # we can't change a tuple

NameError: name 'tuple1' is not defined

In [65]:
tuple1[1]

NameError: name 'tuple1' is not defined

## - Exercice on lists:


        1- Create a list named "my_notes" which contains the following numbers:
                     19,7,15,9,10,6,18,10,16,14,13,10,2,20,17,8,12,10,11,4

        2- Calculate the overall average of this class of 20 students and put the result in a variable called "general_note"

        3- Find the lowest score and the highest score

        4- Sort the list of notes from largest to smallest
        
        5- Replace note 2 by 6
        
        6- Count the number of notes equal to 10 in the class

        7- Count the number of notes equal to 10 in the class
        
        8- Find the number of students with a grade> 10

1- Création de la liste mes notes 

In [57]:
mes_notes=[19,7,15,9,10,6,18,10,16,14,13,10,2,20,17,8,12,10,11,4]

In [58]:
mes_notes

[19, 7, 15, 9, 10, 6, 18, 10, 16, 14, 13, 10, 2, 20, 17, 8, 12, 10, 11, 4]

2 - calcul de la moyenne  générale et assignation du résultat dans une variable: on va importer la librairie mathématique numpy 

In [59]:
import numpy
moyenne_generale=numpy.mean(mes_notes)

In [60]:
moyenne_generale

11.55

3- trouver la note la plus petite et la note la plus grande: fonctions min() et max()

In [61]:
min(mes_notes)

2

In [62]:
max(mes_notes)

20

- trier les notes de la plus grande à la plus petite: 2 méthodes 
    - methode 1 : 

In [63]:
mes_notes.sort()

In [64]:
mes_notes

[2, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [65]:
mes_notes.reverse()

In [66]:
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 2]

   - Méthode 2: utilisation de l'option reverse de la méthode .sort() 

In [67]:
help(mes_notes.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Stable sort *IN PLACE*.



In [68]:
mes_notes.sort(reverse=True)

In [69]:
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 2]

 - Modifier la note 2 par 6 

In [70]:
mes_notes[19]=6

In [71]:
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 6]

- combien d'élèves ont 10 ? : méthode count()

In [72]:
mes_notes.count(10)

4

- Combien d'élèves ont une note supérieur à 10: on va passer par un array ou un tableau, grâce à ce type, on pourra faire une comparaison

In [73]:
mes_notes_array=numpy.asarray(mes_notes)

In [74]:
mes_notes_array

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10,  9,  8,  7,
        6,  4,  6])

In [75]:
mes_notes_array[mes_notes_array>10] # affichage des notes supérieures à 10 

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [76]:
mes_notes_array>10 # cette opération est un masque avec des booléens

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [77]:
len(mes_notes_array[mes_notes_array>10])

10

In [78]:
mes_notes_array[mes_notes_array>10]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])